@extends('layouts.app')
@section('title', 'Terms & Conditions - Readiwork')

@section('content')
<section class="svc-page-hero">
    <div class="container">
        <h1 class="svc-page-title">Terms &amp; Conditions</h1>
        <p class="svc-page-sub">Please read these terms carefully before using the Readiwork platform.</p>
        <p style="color:rgba(255,255,255,0.45);font-size:.85rem;margin-top:10px;">Last updated: March 2026</p>
    </div>
</section>

<section class="legal-section">
    <div class="container legal-layout">
        <nav class="legal-toc" id="legalToc">
            <p class="legal-toc-heading">On this page</p>
            <a href="#section-1">1. Definitions</a>
            <a href="#section-2">2. Acceptance of Terms</a>
            <a href="#section-3">3. Use of the Platform</a>
            <a href="#section-4">4. Credit Information Sharing &amp; Bureau Check Consent Clause</a>
            <a href="#section-5">5. Data Protection</a>
            <a href="#section-6">6. Fees &amp; Billing</a>
            <a href="#section-7">7. API Usage &amp; Fair Use</a>
            <a href="#section-8">8. Intellectual Property</a>
            <a href="#section-9">9. Limitation of Liability</a>
            <a href="#section-10">10. Termination</a>
            <a href="#section-11">11. Governing Law</a>
            <a href="#section-12">12. Contact Us</a>
        </nav>

        <div class="legal-body">
            <div class="legal-intro-box">
                <i class="fa-solid fa-circle-info"></i>
                <p>These Terms &amp; Conditions govern your access to and use of the Readiwork API platform and related services. By registering an account or using our API, you agree to be bound by these terms.</p>
            </div>

            <div class="legal-section-block" id="section-1">
                <h2><span class="legal-num">1</span> Definitions</h2>
                <ul>
                    <li><strong>"Readiwork" / "we" / "us"</strong> means Readiwork Limited, a company registered in Kenya.</li>
                    <li><strong>"Client" / "you"</strong> means any business or individual that registers for and uses the Readiwork platform.</li>
                    <li><strong>"Platform"</strong> means the Readiwork API, dashboard, and all related services provided at readiwork.co.ke.</li>
                    <li><strong>"End User"</strong> means the individual whose credit or identity information is being checked by the Client via the Platform.</li>
                    <li><strong>"Credit Bureau"</strong> means a licensed Credit Reference Bureau regulated by the Central Bank of Kenya.</li>
                    <li><strong>"API"</strong> means the application programming interface that enables Clients to access credit checking and identity verification services.</li>
                    <li><strong>"Credits"</strong> means the prepaid units used to pay for API calls on the Platform.</li>
                    <li><strong>"AI Analysis"</strong> means automated, model-based scoring, classification, and risk insights generated by Readiwork systems.</li>
                </ul>
            </div>

            <div class="legal-section-block" id="section-2">
                <h2><span class="legal-num">2</span> Acceptance of Terms</h2>
                <p>By creating an account, accessing the API, or using any part of the Platform, you confirm that:</p>
                <ul>
                    <li>You have read, understood, and agree to these Terms &amp; Conditions.</li>
                    <li>You are authorised to enter into this agreement on behalf of your organisation (if applicable).</li>
                    <li>You are at least 18 years of age.</li>
                    <li>Your use of the Platform will comply with all applicable Kenyan laws and regulations.</li>
                </ul>
                <p>We reserve the right to update these terms at any time. Continued use of the Platform after any update constitutes acceptance of the revised terms.</p>
            </div>

            <div class="legal-section-block" id="section-3">
                <h2><span class="legal-num">3</span> Use of the Platform</h2>
                <p>You agree to use the Platform only for lawful purposes and in accordance with these Terms. You must not:</p>
                <ul>
                    <li>Use the Platform to check individuals without their prior written consent.</li>
                    <li>Resell, sublicense, or redistribute credit data obtained through the Platform without authorisation from Readiwork.</li>
                    <li>Use the Platform to discriminate against individuals in violation of applicable law.</li>
                    <li>Attempt to reverse-engineer, scrape, or circumvent any technical restrictions of the API.</li>
                    <li>Share your API credentials with unauthorised third parties.</li>
                    <li>Use the Platform for any purpose other than legitimate credit assessment, identity verification, AI-assisted risk analysis, or related lawful activities.</li>
                </ul>
            </div>

            <div class="legal-section-block" id="section-4">
                <h2><span class="legal-num">4</span> Credit Information Sharing &amp; Bureau Check Consent Clause</h2>
                <div class="legal-consent-box">
                    <div class="legal-consent-icon"><i class="fa-solid fa-file-signature"></i></div>
                    <div class="legal-consent-body">
                        <p class="legal-consent-label">Required Consent,  End User Declaration</p>
                        <p>I, <em>(Client's Full Name)</em>, hereby expressly authorize Readiwork Limited (acting on behalf of the subscribing institution) to access, obtain, and review my credit information from any duly licensed and regulated Credit Reference Bureau in accordance with the applicable laws and regulations.</p>
                        <p>I understand that this consent allows Readiwork Limited to make credit inquiries and perform AI-assisted analysis for purposes including credit assessment, risk evaluation, account review, and related lawful purposes connected to my application and/or existing credit facilities.</p>
                        <p>I further acknowledge that the information obtained may be used in accordance with the Data Protection Act and other relevant regulatory requirements.</p>
                        <p>By signing below, I confirm that I have read, understood, and voluntarily agree to the above terms.</p>
                        <p>Client Name: ___________________________</p>
                        <p>Signature: _______________________________</p>
                        <p>Date: __________________________________</p>
                    </div>
                </div>
                <h3>4.1 Client Obligations Regarding Consent</h3>
                <p>As a Client using the Readiwork Platform to run credit or identity checks on individuals, you are solely responsible for:</p>
                <ul>
                    <li>Obtaining the above consent from each End User before initiating any check through the Platform.</li>
                    <li>Maintaining a record of signed consent forms for each End User checked.</li>
                    <li>Ensuring consent is obtained in plain language that the End User understands.</li>
                    <li>Providing the End User with information on how the results will be used.</li>
                </ul>
                <h3>4.2 Release of Liability</h3>
                <p>The End User further releases Readiwork Limited and its officers, employees, and agents from all claims, actions, or proceedings of whatsoever nature arising from the sharing and access of credit information for the purposes stated above.</p>
            </div>

            <div class="legal-section-block" id="section-5">
                <h2><span class="legal-num">5</span> Data Protection</h2>
                <p>Readiwork is committed to protecting personal data in accordance with the <strong>Kenya Data Protection Act, 2019</strong>.</p>
                <ul>
                    <li>Readiwork acts as a <strong>data processor</strong> on behalf of Clients, who are the data controllers for their End Users' information.</li>
                    <li>We do not store, sell, or re-process credit data beyond what is necessary to complete the requested API transaction.</li>
                    <li>Credit data returned from the bureau is transmitted directly to you and is not retained on our servers after the API response is delivered.</li>
                    <li>Clients must have a valid lawful basis for processing End Users' personal data and must maintain their own privacy policy disclosing such use.</li>
                </ul>
            </div>

            <div class="legal-section-block" id="section-6">
                <h2><span class="legal-num">6</span> Fees &amp; Billing</h2>
                <ul>
                    <li>The Platform operates on a <strong>prepaid credit model</strong>. Credits must be purchased in advance before API calls can be made.</li>
                    <li>All prices are displayed in Kenya Shillings (KSh). VAT at 16% is added at checkout.</li>
                    <li>Credits are non-refundable once purchased, except where required by law.</li>
                    <li>Credits do not expire provided your account remains active.</li>
                    <li>We reserve the right to change pricing with reasonable notice.</li>
                    <li>Invoices and receipts are available for download from your dashboard.</li>
                </ul>
            </div>

            <div class="legal-section-block" id="section-7">
                <h2><span class="legal-num">7</span> API Usage &amp; Fair Use</h2>
                <ul>
                    <li>Your API key is personal to your account and must not be shared.</li>
                    <li>AI-generated outputs and risk insights are advisory tools and must be used alongside your institution's independent review and regulatory obligations.</li>
                    <li>We reserve the right to apply rate limits to protect platform stability.</li>
                    <li>Automated bulk lookups unrelated to genuine credit assessment are prohibited.</li>
                    <li>We may suspend accounts that exhibit unusual or abusive usage patterns without notice.</li>
                    <li>You are responsible for the security of your API key. Report any suspected compromise to us immediately at <a href="mailto:hello@readiwork.co.ke">hello@readiwork.co.ke</a>.</li>
                </ul>
            </div>

            <div class="legal-section-block" id="section-8">
                <h2><span class="legal-num">8</span> Intellectual Property</h2>
                <p>All content, software, branding, and documentation on the Platform is the property of Readiwork Limited or its licensors. You may not copy, modify, or distribute any part of the Platform without written permission.</p>
                <p>Credit data retrieved through the API remains the property of the relevant Credit Reference Bureau and is governed by their terms of use.</p>
            </div>

            <div class="legal-section-block" id="section-9">
                <h2><span class="legal-num">9</span> Limitation of Liability</h2>
                <p>To the maximum extent permitted by law:</p>
                <ul>
                    <li>Readiwork is not liable for any loss or damage resulting from decisions made by you or your institution based on credit data or AI-generated analysis returned through the Platform.</li>
                    <li>We do not guarantee the accuracy or completeness of credit information provided by the Credit Reference Bureau.</li>
                    <li>Our total liability to you for any claim shall not exceed the total credits you purchased in the 3 months preceding the claim.</li>
                    <li>We are not liable for any indirect, incidental, or consequential loss arising from use of the Platform.</li>
                </ul>
            </div>

            <div class="legal-section-block" id="section-10">
                <h2><span class="legal-num">10</span> Termination</h2>
                <p>Either party may terminate the account at any time. Readiwork may suspend or terminate your account immediately if you breach any provision of these Terms, we are required to do so by law or a regulatory authority, or your account is used for fraudulent or unlawful activity.</p>
                <p>On termination, unused credits will be refunded at our discretion, unless termination was due to a breach on your part.</p>
            </div>

            <div class="legal-section-block" id="section-11">
                <h2><span class="legal-num">11</span> Governing Law</h2>
                <p>These Terms are governed by and construed in accordance with the laws of the Republic of Kenya. Any disputes arising shall be subject to the exclusive jurisdiction of the Kenyan courts.</p>
            </div>

            <div class="legal-section-block" id="section-12">
                <h2><span class="legal-num">12</span> Contact Us</h2>
                <p>If you have any questions about these Terms &amp; Conditions, please contact us:</p>
                <div class="legal-contact-grid">
                    <div class="legal-contact-item"><i class="fa-solid fa-envelope"></i><div><strong>Email</strong><a href="mailto:info@readi.work">info@readi.work</a></div></div>
                    <div class="legal-contact-item"><i class="fa-solid fa-phone"></i><div><strong>Phone</strong><a href="tel:+254722175570">+254 722175570</a></div></div>
                    <div class="legal-contact-item"><i class="fa-solid fa-location-dot"></i><div><strong>Address</strong><span>Nairobi, Kenya</span></div></div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection
